name: Build for Linux

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build binary for Linux
      run: pyinstaller --onefile --noconsole --add-data "config.ini:." main.py
    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v4
      with:
        name: diploma-system-linux
        path: dist/main
